# Generated by Django 4.1.5 on 2023-01-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GraphImages",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=50)),
                ("image", models.FileField(upload_to="graph_images/")),
            ],
        ),
    ]
