import os  # Generated by Django 4.2.1 on 2023-05-25 21:14
from django.core.files import File

from django.db import migrations


def bootstrap_fmri_image(apps, schema_editor):
    GraphImage = apps.get_model("configuration", "GraphImage")
    file_path = os.path.join(os.path.dirname(os.path.abspath(os.path.dirname(__file__))), "data/fmri_052023.svg")
    with open(file_path, "rb") as f:
        fmri_image = File(f, name="fmri_052023.svg")
        graph_image = GraphImage(key="fmri", image=fmri_image)
        graph_image.save()


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_rename_graphimages_graphimage'),
    ]

    operations = [
        migrations.RunPython(bootstrap_fmri_image, reverse_code=migrations.RunPython.noop)

    ]

