# Generated by Django 4.1.4 on 2023-01-19 22:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='academic_affiliation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='academic_stage',
            field=models.CharField(blank=True, choices=[('undergraduate_student', 'Undergraduate student'), ('graduate_student', 'Graduate student'), ('postdoctoral_fellow', 'Postdoctoral fellow'), ('principle_researcher', 'Principle researcher'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1900, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2100, 1, 1))]),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('not_reporting', 'Not Reporting')], max_length=50, null=True),
        ),
    ]
