# Generated by Django 4.2.2 on 2023-07-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_self_identified_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='academic_stage',
            field=models.CharField(blank=True, choices=[('undergraduate_student', 'Undergraduate student'), ('graduate_student', 'Graduate student'), ('postdoctoral_fellow', 'Postdoctoral fellow'), ('principle_researcher', 'Principle researcher'), ('other', 'Other'), ('non_academic', 'Non academic')], max_length=50, null=True),
        ),
    ]
