version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
    - dependency-name: "whitenoise"
    - dependency-name: "pandas"
      versions: [">=2.0"]
    - dependency-name: "numpy"
      versions: [ ">=2.0" ]
    - dependency-name: "boto3"
      update-types: [ "version-update:semver-patch" ]
    - dependency-name: "ruff"
      update-types: [ "version-update:semver-patch" ]