version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_contrast_api
    ports:
      - "8000:8000"
    volumes:
      - ./nginx_compose:/etc/nginx/conf.d
      - ./data/static:/static
      - ./data/media:/media

    depends_on:
      web:
        condition: service_healthy
  db:
    image: postgres:13
    container_name: postgres_contrast_api
    environment:
      - POSTGRES_DB=contrast_api_db #todo
      - POSTGRES_USER=contrast_api_user
      - POSTGRES_PASSWORD=contrast_api_pass
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U contrast_api_user -d contrast_api_db -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      dockerfile: deploy/Dockerfile

    environment:
      - DJANGO_ALLOWED_HOSTS=web,localhost,127.0.0.1
      - DJANGO_CONFIGURATION=Development
      - DJANGO_MEDIA_ROOT=/media/
      - DJANGO_SETTINGS_MODULE=contrast_api.settings
      - DATABASE_URL=postgresql://contrast_api_user:contrast_api_pass@db/contrast_api_db
    command:
      - bash
      - -c
      - |
        python manage.py migrate
        python manage.py createsuperuser --username admin --email admin@admin.com --noinput && cat <<-000 | python manage.py shell
        from django.contrib.auth import get_user_model
        admin = get_user_model().objects.get(username='admin')
        admin.set_password('admin')
        admin.save()
        print('Superuser password updated successfully.')
        000
        cp /srv/app/static/* -r /static/
        gunicorn contrast_api.wsgi --timeout 180 --bind 0.0.0.0

    volumes:
      - ./data/static:/static
      - ./data/media:/media

    expose:
      - "8000"

    depends_on:
      db:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8000/health_check || exit 1"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 5