[tool.poetry]
name = "contrast-api"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">3.10,<3.11"
Django = "^5.0.2"
django-configurations = "^2.5"
dj-database-url = "^2.1.0"
djangorestframework = "^3.14.0"
django-filter = "^23.5"
django-extensions = "^3.2.3"
django-import-export = "^3.3.7"
django-storages = "^1.14"
Pillow = "^10.2.0"
django-cors-headers = "^4.3.1"
django-querycount = "^0.8.3"
gunicorn = "^21.2.0"
djangorestframework-simplejwt = "^5.3.1"
psycopg2 = "^2.9.9"
drf-nested-routers = "^0.93.5"
drf-spectacular = "^0.27.1"
boto3 = ">=1.26.109"
django-nested-inline = "^0.4.6"
django-modeladmin-reorder = {git = "https://github.com/bloodwithmilk25/django-modeladmin-reorder.git", rev = "master"}
django-spa = {git = "https://github.com/VBobCat/django-spa.git", rev = "master"}
django-countries = {git = "https://github.com/SmileyChris/django-countries", rev="58f258402072a18756a15daa81325428382bd946"}
numpy = "^1.26.4"
pandas = "^1.5.3"
whitenoise = "6.2.0"
django-admin-rangefilter = "^0.12.1"
django-anymail = "^10.2"
sentry-sdk = "^1.40.6"
django-two-factor-auth = { extras = ["phonenumbers"], version = "^1.16.0" }
django-simple-history = "^3.5.0"

[tool.poetry.dev-dependencies]
pytest = "^8.0.1"
ruff = "^0.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120

# Never enforce `E501` (line length violations).
lint.ignore = ["E501"]