[tool.poetry]
name = "contrast-api"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">3.10,<3.11"
Django = "^4.1"
django-configurations = "^2.4"
dj-database-url = "^1.0.0"
djangorestframework = "^3.14.0"
django-filter = "^22.1"
django-extensions = "^3.2.1"
django-import-export = "^3.1.0"
django-storages = "^1.13.1"
Pillow = "^9.4.0"
django-cors-headers = "^3.14.0"
django-querycount = "^0.8.3"
gunicorn = "^20.1.0"
djangorestframework-simplejwt = "^5.2.1"
psycopg2 = "^2.9.4"
drf-nested-routers = "^0.93.4"
drf-spectacular = "^0.26.0"
boto3 = ">=1.26"
django-nested-inline = "^0.4.5"
django-modeladmin-reorder = {git = "https://github.com/bloodwithmilk25/django-modeladmin-reorder.git", rev = "master"}
django-countries = "^7.5.1"

[tool.poetry.dev-dependencies]
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
