# Generated by Django 4.2.7 on 2023-11-28 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("approval_process", "0003_alter_approvalprocess_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approvalcomment",
            options={"ordering": ("created_at",)},
        ),
    ]
