# Generated by Django 5.0.4 on 2024-05-07 10:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0058_alter_historicaltask_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnConMainParadigm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnConModalityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'stimulus modalities',
            },
        ),
        migrations.CreateModel(
            name='UnConProcessingMainDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnConsciousnessMeasurePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnConsciousnessMeasureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnConStimulusCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'stimulus categories',
            },
        ),
        migrations.CreateModel(
            name='UnConSuppressionMethodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnConTaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnConExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(1, 'Neuroscientific'), (2, 'Behavioral'), (3, 'Both')], default=2)),
                ('is_target_stimulus', models.BooleanField(default=False, verbose_name='are there also non-suppressed stimuli')),
                ('is_target_same_as_suppressed_stimulus', models.BooleanField(default=False, verbose_name='is the non-suppressed stimulus the same as the suppressed stimulus')),
                ('consciousness_measures_notes', models.TextField(blank=True, null=True)),
                ('experiment_findings_notes', models.TextField(blank=True, null=True)),
                ('significance', models.CharField(blank=True, choices=[('Negative', 'Negative'), ('Positive', 'Positive'), ('Mixed', 'Mixed')], max_length=10, null=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uncon_experiments', to='studies.study')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalUnConSample',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type', models.CharField(choices=[('healthy_adults', 'Healthy adults'), ('Healthy_college_students', 'Healthy college students'), ('children', 'Children'), ('patients_adults', 'Patients (adults)'), ('patients_children', 'Patients (children)'), ('non_human', 'Non-human'), ('computer', 'Computer')], max_length=30)),
                ('size_included', models.IntegerField()),
                ('size_total', models.IntegerField()),
                ('size_excluded', models.IntegerField(blank=True, null=True, verbose_name='how many participants were excluded based on awareness measure?')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uncontrast_studies.unconexperiment')),
            ],
            options={
                'verbose_name': 'historical un con sample',
                'verbose_name_plural': 'historical un con samples',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUnConFinding',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('outcome', models.CharField(max_length=30)),
                ('is_significant', models.BooleanField(verbose_name='was the effect significant')),
                ('is_important', models.BooleanField(default=True, verbose_name='was the finding important')),
                ('number_of_trials', models.PositiveSmallIntegerField(default=1, verbose_name='number of trials for the task')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uncontrast_studies.unconexperiment')),
            ],
            options={
                'verbose_name': 'historical un con finding',
                'verbose_name_plural': 'historical un con findings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UnConFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=30)),
                ('is_significant', models.BooleanField(verbose_name='was the effect significant')),
                ('is_important', models.BooleanField(default=True, verbose_name='was the finding important')),
                ('number_of_trials', models.PositiveSmallIntegerField(default=1, verbose_name='number of trials for the task')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='uncontrast_studies.unconexperiment')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalUnConSpecificParadigm',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('main', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uncontrast_studies.unconmainparadigm')),
            ],
            options={
                'verbose_name': 'historical un con specific paradigm',
                'verbose_name_plural': 'historical un con specific paradigms',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UnConProcessingDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_domains', to='uncontrast_studies.unconexperiment')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_domains', to='uncontrast_studies.unconprocessingmaindomain')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalUnConProcessingDomain',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uncontrast_studies.unconexperiment')),
                ('main', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uncontrast_studies.unconprocessingmaindomain')),
            ],
            options={
                'verbose_name': 'historical un con processing domain',
                'verbose_name_plural': 'historical un con processing domains',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UnConSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('healthy_adults', 'Healthy adults'), ('Healthy_college_students', 'Healthy college students'), ('children', 'Children'), ('patients_adults', 'Patients (adults)'), ('patients_children', 'Patients (children)'), ('non_human', 'Non-human'), ('computer', 'Computer')], max_length=30)),
                ('size_included', models.IntegerField()),
                ('size_total', models.IntegerField()),
                ('size_excluded', models.IntegerField(blank=True, null=True, verbose_name='how many participants were excluded based on awareness measure?')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='uncontrast_studies.unconexperiment')),
            ],
        ),
        migrations.CreateModel(
            name='UnConsciousnessMeasureSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unconsciousness_measure_sub_types', to='uncontrast_studies.unconsciousnessmeasuretype')),
            ],
        ),
        migrations.CreateModel(
            name='UnConsciousnessMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_trials', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='consciousness measure # of trials for the objective measure')),
                ('number_of_participants_in_awareness_test', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_cm_same_participants_as_task', models.BooleanField(verbose_name='was consciousness measure taken from the same participants as the main task')),
                ('is_performance_above_chance', models.BooleanField()),
                ('is_trial_excluded_based_on_measure', models.BooleanField(verbose_name='were trials excluded from the analysis based on the measure')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unconsciousness_measures', to='uncontrast_studies.unconexperiment')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unconsciousness_measures', to='uncontrast_studies.unconsciousnessmeasurephase')),
                ('sub_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unconsciousness_measures', to='uncontrast_studies.unconsciousnessmeasuresubtype')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unconsciousness_measures', to='uncontrast_studies.unconsciousnessmeasuretype')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalUnConsciousnessMeasure',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number_of_trials', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='consciousness measure # of trials for the objective measure')),
                ('number_of_participants_in_awareness_test', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_cm_same_participants_as_task', models.BooleanField(verbose_name='was consciousness measure taken from the same participants as the main task')),
                ('is_performance_above_chance', models.BooleanField()),
                ('is_trial_excluded_based_on_measure', models.BooleanField(verbose_name='were trials excluded from the analysis based on the measure')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uncontrast_studies.unconexperiment')),
                ('phase', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uncontrast_studies.unconsciousnessmeasurephase')),
                ('sub_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uncontrast_studies.unconsciousnessmeasuresubtype')),
                ('type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uncontrast_studies.unconsciousnessmeasuretype')),
            ],
            options={
                'verbose_name': 'historical un consciousness measure',
                'verbose_name_plural': 'historical un consciousness measures',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UnConSpecificParadigm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specific_paradigm', to='uncontrast_studies.unconmainparadigm')),
            ],
        ),
        migrations.AddField(
            model_name='unconexperiment',
            name='paradigm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiments', to='uncontrast_studies.unconspecificparadigm'),
        ),
        migrations.CreateModel(
            name='HistoricalUnConExperiment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(1, 'Neuroscientific'), (2, 'Behavioral'), (3, 'Both')], default=2)),
                ('is_target_stimulus', models.BooleanField(default=False, verbose_name='are there also non-suppressed stimuli')),
                ('is_target_same_as_suppressed_stimulus', models.BooleanField(default=False, verbose_name='is the non-suppressed stimulus the same as the suppressed stimulus')),
                ('consciousness_measures_notes', models.TextField(blank=True, null=True)),
                ('experiment_findings_notes', models.TextField(blank=True, null=True)),
                ('significance', models.CharField(blank=True, choices=[('Negative', 'Negative'), ('Positive', 'Positive'), ('Mixed', 'Mixed')], max_length=10, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='studies.study')),
                ('paradigm', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uncontrast_studies.unconspecificparadigm')),
            ],
            options={
                'verbose_name': 'historical un con experiment',
                'verbose_name_plural': 'historical un con experiments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UnConStimulusSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_categories', to='uncontrast_studies.unconstimuluscategory')),
            ],
            options={
                'verbose_name_plural': 'stimulus sub categories',
            },
        ),
        migrations.CreateModel(
            name='HistoricalUnConTargetStimulus',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number_of_stimuli', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uncontrast_studies.unconexperiment')),
                ('modality', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uncontrast_studies.unconmodalitytype')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uncontrast_studies.unconstimuluscategory')),
                ('sub_category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uncontrast_studies.unconstimulussubcategory')),
            ],
            options={
                'verbose_name': 'historical un con target stimulus',
                'verbose_name_plural': 'historical target stimuli',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUnConSuppressedStimulus',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('mode_of_presentation', models.CharField(choices=[('liminal', 'Liminal'), ('subliminal', 'Subliminal')], max_length=30)),
                ('duration', models.DecimalField(decimal_places=3, max_digits=10)),
                ('soa', models.DecimalField(decimal_places=3, max_digits=10)),
                ('number_of_stimuli', models.PositiveSmallIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uncontrast_studies.unconexperiment')),
                ('modality', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uncontrast_studies.unconmodalitytype')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uncontrast_studies.unconstimuluscategory')),
                ('sub_category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uncontrast_studies.unconstimulussubcategory')),
            ],
            options={
                'verbose_name': 'historical un con suppressed stimulus',
                'verbose_name_plural': 'historical suppressed stimuli',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UnConSuppressedStimulus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_presentation', models.CharField(choices=[('liminal', 'Liminal'), ('subliminal', 'Subliminal')], max_length=30)),
                ('duration', models.DecimalField(decimal_places=3, max_digits=10)),
                ('soa', models.DecimalField(decimal_places=3, max_digits=10)),
                ('number_of_stimuli', models.PositiveSmallIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppressed_stimuli', to='uncontrast_studies.unconstimuluscategory')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppressed_stimuli', to='uncontrast_studies.unconexperiment')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppressed_stimuli', to='uncontrast_studies.unconmodalitytype')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppressed_stimuli', to='uncontrast_studies.unconstimulussubcategory')),
            ],
            options={
                'verbose_name_plural': 'suppressed stimuli',
            },
        ),
        migrations.CreateModel(
            name='UnConSuppressionMethodSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='uncontrast_studies.unconsuppressionmethodtype')),
            ],
        ),
        migrations.CreateModel(
            name='UnConSuppressionMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppression_methods', to='uncontrast_studies.unconexperiment')),
                ('sub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppression_methods', to='uncontrast_studies.unconsuppressionmethodsubtype')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppression_methods', to='uncontrast_studies.unconsuppressionmethodtype')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalUnConSuppressionMethod',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uncontrast_studies.unconexperiment')),
                ('sub_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uncontrast_studies.unconsuppressionmethodsubtype')),
                ('type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uncontrast_studies.unconsuppressionmethodtype')),
            ],
            options={
                'verbose_name': 'historical un con suppression method',
                'verbose_name_plural': 'historical un con suppression methods',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UnConTargetStimulus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_stimuli', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_stimuli', to='uncontrast_studies.unconstimuluscategory')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_stimuli', to='uncontrast_studies.unconexperiment')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_stimuli', to='uncontrast_studies.unconmodalitytype')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_stimuli', to='uncontrast_studies.unconstimulussubcategory')),
            ],
            options={
                'verbose_name_plural': 'target stimuli',
            },
        ),
        migrations.CreateModel(
            name='UnConTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='uncontrast_studies.unconexperiment')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='uncontrast_studies.uncontasktype')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalUnConTask',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uncontrast_studies.unconexperiment')),
                ('type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uncontrast_studies.uncontasktype')),
            ],
            options={
                'verbose_name': 'historical un con task',
                'verbose_name_plural': 'historical un con tasks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
