# Generated by Django 5.0.4 on 2024-05-07 10:53

from django.db import migrations

from configuration.uncontrast_initial_data_types import (
    uncon_paradigms,
    uncon_tasks,
    uncon_stimulus_categories,
    uncon_stimulus_modalities,
    uncon_suppression_methods,
    uncon_processing_domains,
    uncon_consciousness_measures_phases,
    uncon_consciousness_measures_types,
)


def bootstrap_type_uncon_models(apps, schema_editor):
    UnConsciousnessMeasurePhase = apps.get_model("uncontrast_studies", "UnConsciousnessMeasurePhase")
    for phase in uncon_consciousness_measures_phases:
        UnConsciousnessMeasurePhase.objects.get_or_create(name=phase)

    UnConsciousnessMeasureType = apps.get_model("uncontrast_studies", "UnConsciousnessMeasureType")
    UnConsciousnessMeasureSubType = apps.get_model("uncontrast_studies", "UnConsciousnessMeasureSubType")
    for main_type, list_of_specific_types in uncon_consciousness_measures_types.items():
        UnConsciousnessMeasureType.objects.get_or_create(name=main_type)
        for specific_type in list_of_specific_types:
            parent_type = UnConsciousnessMeasureType.objects.get(name=main_type)
            UnConsciousnessMeasureSubType.objects.get_or_create(name=specific_type, type=parent_type)

    UnConMainParadigm = apps.get_model("uncontrast_studies", "UnConMainParadigm")
    UnConSpecificParadigm = apps.get_model("uncontrast_studies", "UnConSpecificParadigm")
    for paradigm, list_of_specific_paradigms in uncon_paradigms.items():
        UnConMainParadigm.objects.get_or_create(name=paradigm)
        for specific_paradigm in list_of_specific_paradigms:
            main = UnConMainParadigm.objects.get(name=paradigm)
            UnConSpecificParadigm.objects.get_or_create(name=specific_paradigm, main=main)


    UnConProcessingMainDomain = apps.get_model("uncontrast_studies", "UnConProcessingMainDomain")
    for domain in uncon_processing_domains:
        UnConProcessingMainDomain.objects.get_or_create(name=domain)

    UnConModalityType = apps.get_model("uncontrast_studies", "UnConModalityType")
    for modality in uncon_stimulus_modalities:
        UnConModalityType.objects.get_or_create(name=modality)

    UnConStimulusCategory = apps.get_model("uncontrast_studies", "UnConStimulusCategory")
    UnConStimulusSubCategory = apps.get_model("uncontrast_studies", "UnConStimulusSubCategory")
    for category, list_of_sub_categories in uncon_stimulus_categories.items():
        UnConStimulusCategory.objects.get_or_create(name=category)
        for sub_category in list_of_sub_categories:
            parent = UnConStimulusCategory.objects.get(name=category)
            UnConStimulusSubCategory.objects.get_or_create(name=sub_category, parent=parent)

    UnConSuppressionMethodType = apps.get_model("uncontrast_studies", "UnConSuppressionMethodType")
    UnConSuppressionMethodSubType = apps.get_model("uncontrast_studies", "UnConSuppressionMethodSubType")
    for main_method, list_of_specific_methods in uncon_suppression_methods.items():
        UnConSuppressionMethodType.objects.get_or_create(name=main_method)
        for specific_method in list_of_specific_methods:
            parent = UnConSuppressionMethodType.objects.get(name=main_method)
            UnConSuppressionMethodSubType.objects.get_or_create(name=specific_method, parent=parent)

    UnConTaskType = apps.get_model("uncontrast_studies", "UnConTaskType")
    for task in uncon_tasks:
        UnConTaskType.objects.get_or_create(name=task)


class Migration(migrations.Migration):
    dependencies = [
        ("uncontrast_studies", "0001_initial"),
    ]

    operations = [migrations.RunPython(bootstrap_type_uncon_models, reverse_code=migrations.RunPython.noop)]
