# Generated by Django 5.0.3 on 2024-04-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uncontrast_studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalunconsample',
            name='type',
            field=models.CharField(choices=[('healthy_adults', 'Healthy adults'), ('Healthy_college_students', 'Healthy college students'), ('children', 'Children'), ('patients_adults', 'Patients (adults)'), ('patients_children', 'Patients (children)'), ('non_human', 'Non-human'), ('computer', 'Computer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='unconsample',
            name='type',
            field=models.CharField(choices=[('healthy_adults', 'Healthy adults'), ('Healthy_college_students', 'Healthy college students'), ('children', 'Children'), ('patients_adults', 'Patients (adults)'), ('patients_children', 'Patients (children)'), ('non_human', 'Non-human'), ('computer', 'Computer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='unconsciousnessmeasurephase',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='unconsciousnessmeasuretype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
