# Generated by Django 5.0.6 on 2024-06-17 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uncontrast_studies", "0002_auto_20240405_1947"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uncontargetstimulus",
            name="suppressed_stimulus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="target_stimuli",
                to="uncontrast_studies.unconsuppressedstimulus",
            ),
        ),
    ]
