# Generated by Django 5.0.3 on 2024-04-04 18:26

from django.db import migrations

from configuration.uncontrast_initial_data_types import (
    main_paradigms,
    tasks,
    stimulus_categories,
    stimulus_sub_categories,
    stimulus_modalities,
    main_suppression_methods,
    specific_suppression_methods,
    processing_domains,
    consciousness_measures_main_types,
    consciousness_measures_phases,
    consciousness_measures_specific_types
)


def bootstrap_type_uncon_models(apps, schema_editor):
    UnConsciousnessMeasurePhase = apps.get_model("uncontrast_studies", "UnConsciousnessMeasurePhase")
    for phase in consciousness_measures_phases:
        UnConsciousnessMeasurePhase.objects.get_or_create(name=phase)

    UnConsciousnessMeasureType = apps.get_model("uncontrast_studies", "UnConsciousnessMeasureType")
    for main_type in consciousness_measures_main_types:
        UnConsciousnessMeasureType.objects.get_or_create(name=main_type)

    UnConsciousnessMeasureSubType = apps.get_model("uncontrast_studies", "UnConsciousnessMeasureSubType")
    for main_type, list_of_specific_types in consciousness_measures_specific_types.items():
        for specific_type in list_of_specific_types:
            main_type = UnConsciousnessMeasureType.objects.get(name=main_type)
            UnConsciousnessMeasureSubType.objects.get_or_create(name=specific_type, type=main_type)

    UnConMainParadigm = apps.get_model("uncontrast_studies", "UnConMainParadigm")
    for paradigm in main_paradigms:
        UnConMainParadigm.objects.get_or_create(name=paradigm)

    UnConProcessingMainDomain = apps.get_model("uncontrast_studies", "UnConProcessingMainDomain")
    for domain in processing_domains:
        UnConProcessingMainDomain.objects.get_or_create(name=domain)

    UnConModalityType = apps.get_model("uncontrast_studies", "UnConModalityType")
    for modality in stimulus_modalities:
        UnConModalityType.objects.get_or_create(name=modality)

    UnConStimulusCategory = apps.get_model("uncontrast_studies", "UnConStimulusCategory")
    for category in stimulus_categories:
        UnConStimulusCategory.objects.get_or_create(name=category)

    UnConStimulusSubCategory = apps.get_model("uncontrast_studies", "UnConStimulusSubCategory")
    for category, list_of_sub_categories in stimulus_sub_categories.items():
        for sub_category in list_of_sub_categories:
            parent = UnConStimulusCategory.objects.get(name=category)
            UnConStimulusSubCategory.objects.get_or_create(name=sub_category, parent=parent)

    UnConSuppressionMethodType = apps.get_model("uncontrast_studies", "UnConSuppressionMethodType")
    for method in main_suppression_methods:
        UnConSuppressionMethodType.objects.get_or_create(name=method)

    UnConSuppressionMethodSubType = apps.get_model("uncontrast_studies", "UnConSuppressionMethodSubType")
    for main_method, list_of_specific_methods in specific_suppression_methods.items():
        for specific_method in list_of_specific_methods:
            parent = UnConSuppressionMethodType.objects.get(name=main_method)
            UnConSuppressionMethodSubType.objects.get_or_create(name=specific_method, parent=parent)

    UnConTaskType = apps.get_model("uncontrast_studies", "UnConTaskType")
    for task in tasks:
        UnConTaskType.objects.get_or_create(name=task)


class Migration(migrations.Migration):

    dependencies = [
        ('uncontrast_studies', '0002_alter_historicalunconsample_type_and_more'),
    ]

    operations = [migrations.RunPython(bootstrap_type_uncon_models, reverse_code=migrations.RunPython.noop)]
