# Generated by Django 5.0.4 on 2024-05-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uncontrast_studies', '0002_auto_20240405_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unconprocessingdomain',
            name='sub_domain',
        ),
        migrations.RemoveField(
            model_name='historicalunconprocessingdomain',
            name='sub_domain',
        ),
        migrations.DeleteModel(
            name='UnConProcessingSubDomain',
        ),
    ]
