# Generated by Django 5.0.2 on 2024-04-11 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uncontrast_studies", "0002_auto_20240405_1947"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unconprocessingdomain",
            name="main",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="processing_domains",
                to="uncontrast_studies.unconprocessingmaindomain",
            ),
        ),
        migrations.AlterField(
            model_name="unconprocessingdomain",
            name="sub_domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="processing_domains",
                to="uncontrast_studies.unconprocessingsubdomain",
            ),
        ),
    ]
