# Generated by Django 5.0.2 on 2024-04-11 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uncontrast_studies", "0003_alter_unconprocessingdomain_main_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unconsciousnessmeasuresubtype",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="unconsciousness_measure_sub_types",
                to="uncontrast_studies.unconsciousnessmeasuretype",
            ),
        ),
        migrations.AlterField(
            model_name="unconspecificparadigm",
            name="main",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specific_paradigm",
                to="uncontrast_studies.unconmainparadigm",
            ),
        ),
        migrations.AlterField(
            model_name="unconstimulussubcategory",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sub_categories",
                to="uncontrast_studies.unconstimuluscategory",
            ),
        ),
        migrations.AlterField(
            model_name="uncontask",
            name="type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="uncontrast_studies.uncontasktype"),
        ),
    ]
