# Generated by Django 5.0.4 on 2024-05-25 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uncontrast_studies", "0005_alter_historicalunconsample_size_excluded_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnConOutcome",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name="historicalunconfinding",
            name="outcome",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="uncontrast_studies.unconoutcome",
            ),
        ),
        migrations.AlterField(
            model_name="unconfinding",
            name="outcome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="findings",
                to="uncontrast_studies.unconoutcome",
            ),
        ),
    ]
