# Generated by Django 5.0.4 on 2024-05-25 18:00

from django.db import migrations

from configuration.uncontrast_initial_data_types import uncon_finding_outcomes


def bootstrap_type_uncon_outcome(apps, schema_editor):
    UnConOutcome = apps.get_model("uncontrast_studies", "UnConOutcome")
    for outcome in uncon_finding_outcomes:
        UnConOutcome.objects.get_or_create(name=outcome)


class Migration(migrations.Migration):
    dependencies = [
        ("uncontrast_studies", "0006_unconoutcome_alter_historicalunconfinding_outcome_and_more"),
    ]

    operations = [migrations.RunPython(bootstrap_type_uncon_outcome, reverse_code=migrations.RunPython.noop)]
