# Generated by Django 5.0.6 on 2024-06-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uncontrast_studies', '0007_auto_20240525_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalunconsciousnessmeasure',
            name='is_performance_above_chance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unconsciousnessmeasure',
            name='is_performance_above_chance',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
