# Generated by Django 4.1.4 on 2023-01-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='type',
            field=models.CharField(choices=[('healthy_adults', 'Healthy Adults'), ('children', 'Children'), ('patients', 'Patients'), ('non_human', 'Non Human'), ('computer', 'Computer')], max_length=30),
        ),
    ]
