# Generated by Django 4.1.5 on 2023-01-14 15:54

from django.db import migrations

from configuration.initial_setup import finding_tag_types, stimulus_category, stimulus_sub_category


def bootstrap_type_models(apps, schema_editor):
    StimulusCategory = apps.get_model("studies", "StimulusCategory")
    for category in stimulus_category:
        StimulusCategory.objects.get_or_create(name=category)

    StimulusSubCategory = apps.get_model("studies", "StimulusSubCategory")

    for sub_category in stimulus_sub_category["Geometric Shapes"]:
        geometric_shapes = StimulusCategory.objects.get(name='Geometric Shapes')
        StimulusSubCategory.objects.get_or_create(name=sub_category, parent=geometric_shapes)
    for sub_category in stimulus_sub_category["Objects"]:
        objects = StimulusCategory.objects.get(name='Objects')
        StimulusSubCategory.objects.get_or_create(name=sub_category, parent=objects)
    for sub_category in stimulus_sub_category["Sounds"]:
        sounds = StimulusCategory.objects.get(name='Sounds')
        StimulusSubCategory.objects.get_or_create(name=sub_category, parent=sounds)
    for sub_category in stimulus_sub_category["Virtual Reality Objects"]:
        virtual_reality_objects = StimulusCategory.objects.get(name='Virtual Reality Objects')
        StimulusSubCategory.objects.get_or_create(name=sub_category, parent=virtual_reality_objects)

    gratings = StimulusCategory.objects.get(name='Gratings')
    StimulusSubCategory.objects.get_or_create(name="Gabor", parent=gratings)

    letters = StimulusCategory.objects.get(name='Letters')
    StimulusSubCategory.objects.get_or_create(name="Oriented Ts", parent=letters)

    nociceptive_stimulation = StimulusCategory.objects.get(name='Nociceptive stimulation')
    StimulusSubCategory.objects.get_or_create(name="Laser", parent=nociceptive_stimulation)

    noise = StimulusCategory.objects.get(name='Noise')
    StimulusSubCategory.objects.get_or_create(name="White Noise", parent=noise)

    words = StimulusCategory.objects.get(name='Words')
    StimulusSubCategory.objects.get_or_create(name="Emotional", parent=words)




class Migration(migrations.Migration):
    dependencies = [
        ('studies', '0007_alter_stimulussubcategory_parent'),
    ]

    operations = [
        migrations.RunPython(bootstrap_type_models, reverse_code=migrations.RunPython.noop)

    ]
