# Generated by Django 4.1.5 on 2023-01-14 15:54

from django.db import migrations

from configuration.initial_setup import stimulus_category, stimulus_sub_category


def bootstrap_type_models(apps, schema_editor):
    StimulusCategory = apps.get_model("studies", "StimulusCategory")
    for category in stimulus_category:
        StimulusCategory.objects.get_or_create(name=category)

    StimulusSubCategory = apps.get_model("studies", "StimulusSubCategory")

    for category, group_of_sub_categories in stimulus_sub_category.items():
        for sub_category in group_of_sub_categories:
            parent = StimulusCategory.objects.get(name=category)
            StimulusSubCategory.objects.get_or_create(name=sub_category, parent=parent)


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0007_alter_stimulussubcategory_parent"),
    ]

    operations = [migrations.RunPython(bootstrap_type_models, reverse_code=migrations.RunPython.noop)]
