# Generated by Django 4.1.5 on 2023-01-14 15:54

from django.db import migrations

from configuration.initial_setup import stimulus_category, stimulus_sub_category


def bootstrap_type_models(apps, schema_editor):
    StimulusCategory = apps.get_model("studies", "StimulusCategory")
    for category in stimulus_category:
        StimulusCategory.objects.get_or_create(name=category)

    StimulusSubCategory = apps.get_model("studies", "StimulusSubCategory")

    for sub_category in stimulus_sub_category["Geometric_Shapes"]:
        geometric_shapes = StimulusCategory.objects.get(name='Geometric Shapes')
        StimulusSubCategory.objects.get_or_create(name=sub_category, parent=geometric_shapes)

    gratings_kanizsa = StimulusCategory.objects.get(name='Gratings/Kanizsa')
    StimulusSubCategory.objects.get_or_create(name="Gabor", parent=gratings_kanizsa)

    for sub_category in ["Houses",
                         "Clocks",
                         "Domino"]:
        objects = StimulusCategory.objects.get(name='Objects')
        StimulusSubCategory.objects.get_or_create(name=sub_category, parent=objects)

    for sub_category in ["Houses",
                         "Road",
                         "Moon"]:
        virtual_reality_objects = StimulusCategory.objects.get(name='Virtual Reality Objects')
        StimulusSubCategory.objects.get_or_create(name=sub_category, parent=virtual_reality_objects)


class Migration(migrations.Migration):
    dependencies = [
        ('studies', '0007_alter_stimulussubcategory_parent'),
    ]

    operations = [
        migrations.RunPython(bootstrap_type_models, reverse_code=migrations.RunPython.noop)

    ]
