# Generated by Django 4.1.5 on 2023-01-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0008_auto_20230114_1754"),
    ]

    operations = [
        migrations.AlterField(
            model_name="findingtagfamily",
            name="name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="findingtagtype",
            name="name",
            field=models.CharField(max_length=250),
        ),
    ]
