# Generated by Django 4.1.5 on 2023-01-15 12:25

from django.db import migrations

from configuration.initial_setup import finding_tag_types


def bootstrap_type_models(apps, schema_editor):
    FindingTagFamily = apps.get_model("studies", "FindingTagFamily")
    for finding_tag_family in ["Temporal",
                               "Spatial Areas",
                               "Frequency",
                               "miscellaneous (no Family)"]:
        FindingTagFamily.objects.get_or_create(name=finding_tag_family)

    FindingTagType = apps.get_model("studies", "FindingTagType")
    temporal = FindingTagFamily.objects.get(name='Temporal')
    for finding_tag_type in finding_tag_types['Temporal']:

        FindingTagType.objects.get_or_create(name=finding_tag_type, family=temporal)

    spatial_areas = FindingTagFamily.objects.get(name='Spatial Areas')
    for finding_tag_type in finding_tag_types['Spatial_Areas']:

        FindingTagType.objects.get_or_create(name=finding_tag_type, family=spatial_areas)

    frequency = FindingTagFamily.objects.get(name='Frequency')
    for finding_tag_type in ["Alpha",
                             "Beta",
                             "Delta",
                             "Gamma",
                             "Theta"]:
        FindingTagType.objects.get_or_create(name=finding_tag_type, family=frequency)

    miscellaneous = FindingTagFamily.objects.get(name='miscellaneous (no Family)')
    for finding_tag_type in finding_tag_types['miscellaneous']:
        FindingTagType.objects.get_or_create(name=finding_tag_type, family=miscellaneous)

class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0010_merge_20230115_1027'),
    ]

    operations = [
        migrations.RunPython(bootstrap_type_models, reverse_code=migrations.RunPython.noop)

    ]
