# Generated by Django 4.1.4 on 2023-01-09 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0011_auto_20230115_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='study',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='study',
            name='references',
        ),
    ]
