# Generated by Django 4.1.5 on 2023-02-06 21:07

from django.db import migrations

from configuration.initial_setup import findings_measures



def bootstrap_type_models(apps, schema_editor):
    MeasureType = apps.get_model("studies", "MeasureType")
    for measure_type in findings_measures.values():
        MeasureType.objects.get_or_create(name=measure_type)




class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0013_rename_key_words_study_authors_key_words_and_more'),
    ]

    operations = [
        migrations.RunPython(bootstrap_type_models, reverse_code=migrations.RunPython.noop)

    ]
