# Generated by Django 4.1.6 on 2023-03-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0021_experiment_notes_alter_sample_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stimulus",
            name="duration",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
