# Generated by Django 4.1.6 on 2023-03-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0022_alter_stimulus_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="findingtag",
            name="band_higher_bound",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="findingtag",
            name="band_lower_bound",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
