# Generated by Django 4.1.6 on 2023-03-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0023_alter_findingtag_band_higher_bound_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="findingtag",
            name="AAL_atlas_tag",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
