# Generated by Django 4.2 on 2023-04-25 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0027_alter_sample_type_alter_stimulus_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consciousnessmeasure",
            name="phase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consciousness_measures",
                to="studies.consciousnessmeasurephasetype",
            ),
        ),
        migrations.AlterField(
            model_name="consciousnessmeasure",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consciousness_measures",
                to="studies.consciousnessmeasuretype",
            ),
        ),
    ]
