# Generated by Django 4.2.1 on 2023-05-17 10:25

from django.db import migrations

from configuration.initial_setup import ParentTheories

acronyms = {
    ParentTheories.GLOBAL_WORKSPACE: "GWT",
    ParentTheories.INTEGRATED_INFORMATION: "IIT",
    ParentTheories.HIGHER_ORDER: "HOT",
    ParentTheories.FIRST_ORDER_AND_PREDICTIVE_PROCESSING: "FOT",
    ParentTheories.OTHER: "Other",
}


def update_parent_theories_acronyms(apps, schema_editor):
    Theory = apps.get_model("studies", "Theory")
    for theory in Theory.objects.filter(parent__isnull=True):
        theory.acronym = acronyms[theory.name]
        theory.save()


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0031_aggregatedinterpretation_parent_theory_acronyms_and_more"),
    ]

    operations = [migrations.RunPython(update_parent_theories_acronyms)]
