# Generated by Django 4.2.1 on 2023-05-17 10:23

from django.db import migrations
from studies.services.aggregated_Interpretations_svc import AggregatedInterpretationDTO, AggregatedInterpretationService
from studies.choices import InterpretationsChoices

def update_aggregate_interpretations(apps, schema_editor):
    Interpretation = apps.get_model("studies", "Interpretation")
    AggregatedInterpretation = apps.get_model("studies", "AggregatedInterpretation")
    non_neutrals = Interpretation.objects.filter(type__in=[InterpretationsChoices.PRO,
                                                           InterpretationsChoices.CHALLENGES])
    experiments_ids = non_neutrals.values_list("experiment_id", flat=True)
    for experiment_id in experiments_ids:
        current_interpretations = Interpretation.objects.filter(experiment_id=experiment_id)
        serialized_interpretations = [
            AggregatedInterpretationDTO(parent_theory_names=item.theory.parent.name,
                                        type=item.type,
                                        parent_theory_acronyms=item.theory.parent.acronym) for item in
            current_interpretations]
        service = AggregatedInterpretationService(serialized_interpretations)
        updated_aggregated_interpretations = service.resolve()
        # remove current ones
        AggregatedInterpretation.objects.filter(experiment_id=experiment_id).delete()
        for aggregated_interpretation in updated_aggregated_interpretations:
            AggregatedInterpretation.objects.create(experiment_id=experiment_id,
                                                    type=aggregated_interpretation.type,
                                                    parent_theory_acronyms=aggregated_interpretation.parent_theory_acronyms,
                                                    parent_theory_names=aggregated_interpretation.parent_theory_names)

class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0032_auto_20230517_1025'),
    ]

    operations = [
        migrations.RunPython(update_aggregate_interpretations)

    ]
