# Generated by Django 4.2.2 on 2023-07-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0035_alter_study_approval_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="affiliations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="study",
            name="corresponding_author_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
