# Generated by Django 4.2.2 on 2023-07-17 12:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0036_alter_study_affiliations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="authors_key_words",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50), default=list, size=None
            ),
        ),
    ]
