# Generated by Django 4.2.4 on 2023-08-15 13:52

from django.db import migrations

from configuration.initial_setup import paradigm_sub_types, paradigms


def bootstrap_paradigm_sub_type(apps, schema_editor):
    Paradigm = apps.get_model("studies", "Paradigm")

    for main_paradigm, group_of_specific_paradigms in paradigms.items():
        parent, created = Paradigm.objects.get_or_create(name=main_paradigm, parent=None, sub_type=None)
        if main_paradigm in paradigm_sub_types.keys():
            for specific_paradigm in group_of_specific_paradigms:
                for sub_type in paradigm_sub_types[main_paradigm]:
                    Paradigm.objects.get_or_create(name=specific_paradigm, parent=parent, sub_type=sub_type)
        for specific_paradigm in group_of_specific_paradigms:
            if specific_paradigm in paradigm_sub_types.keys():
                for sub_type in paradigm_sub_types[specific_paradigm]:
                    Paradigm.objects.get_or_create(name=specific_paradigm, parent=parent, sub_type=sub_type)
                # making sure we don't keep a wrong version of these paradigms
                paradigm_to_delete = Paradigm.objects.get(name=specific_paradigm, parent=parent, sub_type=None)
                paradigm_to_delete.delete()

            else:
                Paradigm.objects.get_or_create(name=specific_paradigm, parent=parent, sub_type=None)


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0042_remove_consciousnessmeasure_description_and_more'),
    ]

    operations = [
        migrations.RunPython(bootstrap_paradigm_sub_type, reverse_code=migrations.RunPython.noop)

    ]
