# Generated by Django 4.2.5 on 2023-11-05 07:23

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("approval_process", "0003_alter_approvalprocess_status"),
        ("studies", "0047_alter_experiment_results_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalTheory",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("acronym", models.CharField(blank=True, max_length=10, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="studies.theory",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical theory",
                "verbose_name_plural": "historical theories",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTechnique",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical technique",
                "verbose_name_plural": "historical techniques",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTask",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="studies.experiment",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="studies.tasktype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical task",
                "verbose_name_plural": "historical tasks",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalStudy",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("DOI", models.CharField(db_index=True, max_length=100)),
                ("title", models.TextField()),
                (
                    "year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                ("corresponding_author_email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "approval_status",
                    models.IntegerField(
                        choices=[(0, "Pending"), (3, "Awaiting Review"), (1, "Approved"), (2, "Rejected")], default=0
                    ),
                ),
                (
                    "authors_key_words",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), default=list, size=None
                    ),
                ),
                ("funding", models.TextField(blank=True, null=True)),
                ("source_title", models.CharField(blank=True, max_length=200, null=True)),
                ("abbreviated_source_title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "countries",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django_countries.fields.CountryField(max_length=2), size=None
                    ),
                ),
                ("affiliations", models.TextField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "approval_process",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="approval_process.approvalprocess",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical study",
                "verbose_name_plural": "historical studies",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalStimulus",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("duration", models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="studies.stimuluscategory",
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="studies.experiment",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modality",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="studies.modalitytype",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="studies.stimulussubcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical stimulus",
                "verbose_name_plural": "historical stimuli",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSample",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("healthy_adults", "Healthy_adults"),
                            ("Healthy_college_students", "Healthy_college_students"),
                            ("children", "Children"),
                            ("patients", "Patients"),
                            ("non_human", "Non_human"),
                            ("computer", "Computer"),
                            ("Young_patients_(children)", "Young_patients_(children)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("total_size", models.IntegerField()),
                ("size_included", models.IntegerField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="studies.experiment",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical sample",
                "verbose_name_plural": "historical samples",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalParadigm",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("sub_type", models.CharField(blank=True, max_length=100, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="studies.paradigm",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical paradigm",
                "verbose_name_plural": "historical paradigms",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMeasure",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("notes", models.TextField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="studies.experiment",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="studies.measuretype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical measure",
                "verbose_name_plural": "historical measures",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFindingTag",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("onset", models.IntegerField(blank=True, null=True, verbose_name="Onset timing in ms")),
                ("offset", models.IntegerField(blank=True, null=True, verbose_name="Offset timing in ms")),
                (
                    "band_lower_bound",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True, verbose_name="Band Lower bound in Hz"
                    ),
                ),
                (
                    "band_higher_bound",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True, verbose_name="Band Higher bound in Hz"
                    ),
                ),
                (
                    "AAL_atlas_tag",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Precentral", "Precentral"),
                            ("Frontal_Sup", "Frontal_Sup"),
                            ("Frontal_Mid", "Frontal_Mid"),
                            ("Frontal_Inf_Oper", "Frontal_Inf_Oper"),
                            ("Frontal_Inf_Tri", "Frontal_Inf_Tri"),
                            ("Frontal_Inf_Orb", "Frontal_Inf_Orb"),
                            ("Rolandic_Oper", "Rolandic_Oper"),
                            ("Supp_Motor_Area", "Supp_Motor_Area"),
                            ("Olfactory", "Olfactory"),
                            ("Frontal_Sup_Med", "Frontal_Sup_Med"),
                            ("Frontal_Med_Orb", "Frontal_Med_Orb"),
                            ("Rectus", "Rectus"),
                            ("OFCmed", "OFCmed"),
                            ("OFCant", "OFCant"),
                            ("OFCpost", "OFCpost"),
                            ("OFClat", "OFClat"),
                            ("Insula", "Insula"),
                            ("Cingulate_Ant", "Cingulate_Ant"),
                            ("Cingulate_Mid", "Cingulate_Mid"),
                            ("Cingulate_Post", "Cingulate_Post"),
                            ("Hippocampus", "Hippocampus"),
                            ("ParaHippocampal", "ParaHippocampal"),
                            ("Amygdala", "Amygdala"),
                            ("Calcarine", "Calcarine"),
                            ("Cuneus", "Cuneus"),
                            ("Lingual", "Lingual"),
                            ("Occipital_Sup", "Occipital_Sup"),
                            ("Occipital_Mid", "Occipital_Mid"),
                            ("Occipital_Inf", "Occipital_Inf"),
                            ("Fusiform", "Fusiform"),
                            ("Postcentral", "Postcentral"),
                            ("Parietal_Sup", "Parietal_Sup"),
                            ("Parietal_Inf", "Parietal_Inf"),
                            ("SupraMarginal", "SupraMarginal"),
                            ("Angular", "Angular"),
                            ("Precuneus", "Precuneus"),
                            ("Paracentral_Lobule", "Paracentral_Lobule"),
                            ("Caudate", "Caudate"),
                            ("Putamen", "Putamen"),
                            ("Pallidum", "Pallidum"),
                            ("Thalamus", "Thalamus"),
                            ("Heschl", "Heschl"),
                            ("Temporal_Sup", "Temporal_Sup"),
                            ("Temporal_Pole_Sup", "Temporal_Pole_Sup"),
                            ("Temporal_Mid", "Temporal_Mid"),
                            ("Temporal_Pole_Mid", "Temporal_Pole_Mid"),
                            ("Temporal_Inf", "Temporal_Inf"),
                            ("Thal_AV", "Thal_AV"),
                            ("Thal_LP", "Thal_LP"),
                            ("Thal_VA", "Thal_VA"),
                            ("Thal_VL", "Thal_VL"),
                            ("Thal_VPL", "Thal_VPL"),
                            ("Thal_IL", "Thal_IL"),
                            ("Thal_RE", "Thal_RE"),
                            ("Thal_MDm", "Thal_MDm"),
                            ("Thal_MDl", "Thal_MDl"),
                            ("Thal_LGN", "Thal_LGN"),
                            ("Thal_MGN", "Thal_MGN"),
                            ("Thal_PuA", "Thal_PuA"),
                            ("Thal_PuM", "Thal_PuM"),
                            ("Thal_PuL", "Thal_PuL"),
                            ("Thal_PuI", "Thal_PuI"),
                        ],
                        max_length=500,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "analysis_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("power", "Power"),
                            ("connectivity", "Connectivity"),
                            ("phi", "Phi"),
                            ("complexity", "Complexity"),
                            ("te", "Te - transfer entropy"),
                            ("pca", "PCA - principal components analysis"),
                            ("lrtc", "LRTC - long-range temporal correlations"),
                            ("microstates", "Microstates"),
                            ("cd", "CD - correlation dimension"),
                            ("clustering", "Clustering"),
                            ("mst", "MST - minimum spanning tree"),
                            ("psd", "PSD - power spectral density"),
                            ("ersp", "ERSP - event-related spectral perturbations"),
                        ],
                        default="power",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        blank=True,
                        choices=[("negative", "Negative"), ("positive", "Positive")],
                        default="positive",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("is_NCC", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="studies.experiment",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="studies.findingtagfamily",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="studies.technique",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="studies.findingtagtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical finding tag",
                "verbose_name_plural": "historical finding tags",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalExperiment",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("results_summary", models.TextField(blank=True, null=True)),
                (
                    "type_of_consciousness",
                    models.CharField(
                        choices=[("content", "Content"), ("state", "State"), ("both", "Both")], max_length=20
                    ),
                ),
                (
                    "is_reporting",
                    models.CharField(
                        choices=[("report", "Report"), ("no_report", "No_report"), ("both", "Both")], max_length=20
                    ),
                ),
                (
                    "theory_driven",
                    models.CharField(
                        choices=[("driven", "Driven"), ("mentioning", "Mentioning"), ("post-hoc", "Post hoc")],
                        max_length=20,
                    ),
                ),
                ("tasks_notes", models.TextField(blank=True, null=True)),
                ("consciousness_measures_notes", models.TextField(blank=True, null=True)),
                ("stimuli_notes", models.TextField(blank=True, null=True)),
                ("paradigms_notes", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.PositiveIntegerField(
                        choices=[(1, "Neuroscientific"), (2, "Behavioral"), (3, "Both")], default=1
                    ),
                ),
                ("sample_notes", models.TextField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="studies.study",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical experiment",
                "verbose_name_plural": "historical experiments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAuthor",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical author",
                "verbose_name_plural": "historical authors",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
