# Generated by Django 4.2.7 on 2023-11-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0049_alter_findingtag_aal_atlas_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstudy",
            name="is_author_submitter",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="study",
            name="is_author_submitter",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
