# Generated by Django 4.2.7 on 2023-12-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0051_alter_study_approval_process'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('name',)},
        ),
    ]
