# Generated by Django 5.0.1 on 2024-02-03 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0052_alter_author_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paradigm",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child_paradigm",
                to="studies.paradigm",
            ),
        ),
    ]
