# Generated by Django 5.0.2 on 2024-03-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0054_alter_findingtag_technique"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstudy",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("Consciousness", "Consciousness"), ("UnConsciousness", "Unconsciousness")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("Consciousness", "Consciousness"), ("UnConsciousness", "Unconsciousness")],
                max_length=20,
                null=True,
            ),
        ),
    ]
