# Generated by Django 5.0.8 on 2024-08-15 19:05

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0059_alter_historicalstudy_authors_key_words_and_more"),
    ]

    original_operations = [
        # migrations.AlterIndexTogether(
        #     name="interpretation",
        #     index_together=set(),
        # ),
        migrations.AddConstraint(
            model_name="interpretation",
            constraint=models.UniqueConstraint(fields=("experiment", "theory"), name="unique_theory"),
        ),
    ]
    testing_operations = []
    if settings.NAME == "testing":
        operations = testing_operations
    else:
        operations = original_operations
    operations = operations
