# Generated by Django 5.1.2 on 2024-10-26 12:34

from django.db import migrations

def add_missing_sub_stimulus_category_other(apps, schema_editor):
    StimulusSubCategory = apps.get_model("studies", "StimulusSubCategory")
    StimulusCategory = apps.get_model("studies", "StimulusCategory")
    Stimulus = apps.get_model("studies", "Stimulus")
    # get all categories that have any sub category
    categories_with_sub_categories = StimulusCategory.objects.filter(stimulussubcategory__isnull=False).distinct()
    # now filter out those that already have a sub category named "Other"
    categories_without_other = categories_with_sub_categories.exclude(stimulussubcategory__name="Other")

    for category in categories_without_other:
        StimulusSubCategory.objects.create(name="Other", parent=category)

    stimuli_to_process = (Stimulus.objects.filter(category__in=categories_with_sub_categories)
                          .filter(sub_category__isnull=True))

    for stimulus in stimuli_to_process:
        stimulus.sub_category = StimulusSubCategory.objects.get(parent=stimulus.category, name="Other")
        stimulus.save()





class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0060_alter_interpretation_index_together_and_more'),
    ]

    operations = [
        migrations.RunPython(add_missing_sub_stimulus_category_other, reverse_code=migrations.RunPython.noop)
    ]
