# Generated by Django 5.1.4 on 2025-02-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0062_alter_modalitytype_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AALAtlasTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name="findingtag",
            name="AAL_atlas_tags",
            field=models.ManyToManyField(blank=True, related_name="finding_tags", to="studies.aalatlastag"),
        ),
    ]
