# Generated by Django 5.1.5 on 2025-02-05 19:32

from django.db import migrations

aal_atlas_labels = [
    "Precentral",
    "Frontal_Sup_2",
    "Frontal_Mid_2",
    "Frontal_Inf_Oper",
    "Frontal_Inf_Tri",
    "Frontal_Inf_Orb_2",
    "Rolandic_Oper",
    "Supp_Motor_Area",
    "Olfactory",
    "Frontal_Sup_Medial",
    "Frontal_Med_Orb",
    "Rectus",
    "OFCmed",
    "OFCant",
    "OFCpost",
    "OFClat",
    "Insula",
    "Cingulate_Mid",
    "Cingulate_Post",
    "Hippocampus",
    "ParaHippocampal",
    "Amygdala",
    "Calcarine",
    "Cuneus",
    "Lingual",
    "Occipital_Sup",
    "Occipital_Mid",
    "Occipital_Inf",
    "Fusiform",
    "Postcentral",
    "Parietal_Sup",
    "Parietal_Inf",
    "SupraMarginal",
    "Angular",
    "Precuneus",
    "Paracentralobule",
    "Caudate",
    "Putamen",
    "Pallidum",
    "Heschl",
    "Temporal_Sup",
    "Temporal_Pole_Sup",
    "Temporal_Mid",
    "Temporal_Pole_Mid",
    "Temporal_Inf",
    "Cerebellum_Crus1",
    "Cerebellum_Crus2",
    "Cerebellum_3",
    "Cerebellum_4_5",
    "Cerebellum_6",
    "Cerebellum_7b",
    "Cerebellum_8",
    "Cerebellum_9",
    "Cerebellum_10",
    "Thal_AV",
    "ThalP",
    "Thal_VA",
    "Thal_VL",
    "Thal_VPL",
    "Thal_IL",
    "Thal_Re",
    "Thal_MDm",
    "Thal_MDl",
    "ThalGN",
    "Thal_MGN",
    "Thal_PuI",
    "Thal_PuM",
    "Thal_PuA",
    "Thal_PuL",
    "ACC_sub",
    "ACC_pre",
    "ACC_sup",
    "N_Acc",
    "VTA",
    "SN_pc",
    "SN_pr",
    "Red_N",
    "LC",
]


def bootstrap_aal_atlas_tags(apps, schema_editor):
    AALAtlasTag = apps.get_model("studies", "AALAtlasTag")

    for label in aal_atlas_labels:
        AALAtlasTag.objects.create(name=label)


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0063_aalatlastag_findingtag_aal_atlas_tags"),
    ]

    operations = [migrations.RunPython(bootstrap_aal_atlas_tags, reverse_code=migrations.RunPython.noop)]
