# Generated by Django 5.1.5 on 2025-02-10 14:59

from django.db import migrations


def remove_mri_from_fmri_experiments(apps, schema_editor):
    """
    Data migration to remove 'MRI' technique from experiments
    that already have 'fMRI' technique.

    """
    Experiment = apps.get_model("studies", "Experiment")
    Technique = apps.get_model("studies", "Technique")

    try:
        fmri_technique = Technique.objects.get(name="fMRI")
        mri_technique = Technique.objects.get(name="MRI")
    except Technique.DoesNotExist:
        print("Warning: Either 'fMRI' or 'MRI' technique not found.")
        return

    experiments_to_modify = Experiment.objects.filter(techniques=fmri_technique).filter(techniques=mri_technique)

    for experiment in experiments_to_modify:
        experiment.techniques.remove(mri_technique)
        experiment.save()
        print(f"Removed MRI technique from Experiment {experiment.id}")


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0064_auto_populate_AAL_atlas_tags"),
    ]

    operations = [
        migrations.RunPython(remove_mri_from_fmri_experiments),
    ]
