parent_theories = ['GNW', 'IIT', 'HOT', 'RPT']

consciousness_measure_types = ["None",
                               "Condition Assessment",
                               "Subjective",
                               "State Induction Assessment",
                               "Sleep Monitoring",
                               "Objective"]

consciousness_measure_phases = ["None",
                                "Post Experiment",
                                "Pre Experiment",
                                "Separate Experiment",
                                "Interminent Questioning",
                                "Trial By Trial"]

modalities = ["Auditory",
              "None",
              "Olfactory",
              "Tactile",
              "Visual"]

main_paradigms = [
        "Abnormal Contents of Consciousness",
        "Alcohol Consumption",
        "Anesthesia",
        "Attentional Manipulation",
        "Caffeine Consumption",
        "Case Study",
        "Change Blindness",
        "Cognitive Tasks",

        "Competition (Binocular)",
        "Competition (Monocular)",
        "Competition (Monoaural)",
        "Competition (Binaural)",
        "Computational Modelling",
        "Contour Integration",
        "Dichoptic Masking",
        "Direct Stimulation",
        "Disorders of Consciousness",
        "Drowsiness",
        "Emotion",
        "Expectation",
        "Familiarity",
        "Family Nurture Intervention",
        "Figure-Ground",
        "Filling In",
        "Fusion (Color)",
        "Genetics",
        "Illusions",
        "Imagination",
        "Lifespan",
        "Locked In Syndrome",
        "Masking",
        "Mirror Masking",
        "Motion Detection",
        "Motion induced Blindness",
        "N-Back",
        "Pain",
        "Passive Exposure",
        "Pop out",
        "Psychedelic Drugs",
        "Repetition Suppression",
        "Resting State",
        "Reward",
        "Sedation",
        "Size Constancy",
        "Sleep",
        "Sperling Like",
        "Stimulus Degradation",
        "SWIFT",
        "Task Relevance",
        "Visual Persistence",
        "Visual Search"]

paradigms = {

    'Abnormal Contents of Consciousness': ["Amusia",
                                           "Blindsight (Abnormal Contents of Consciousness)",
                                           "Conversion Deafness (Abnormal Contents of Consciousness)",
                                           "Hypoactive delirium",
                                           "Neglect",
                                           "Parkinson Disease",
                                           "Schizophrenia",
                                           "Synesthesia",
                                           "Tinnitus (Abnormal Contents of Consciousness)",
                                           "Visual Extinction (Abnormal Contents of Consciousness)"],

    'Alcohol Consumption': ['Alcohol Consumption'],

    'Anesthesia': ["Dexmedetomidine (Anesthesia)",
                   "Dextromethorphan (Anesthesia)",
                   "Enflurane",
                   "Halothane (Anesthesia)",
                   "Isoflurane (Anesthesia)",
                   "Ketamine (Anesthesia)",
                   "Medetomidine (Anesthesia)",
                   "Midazolam",
                   "Pancuronium",
                   "Propofol (Anesthesia)",
                   "Sevoflurane",
                   "Sufentanil",
                   "Urethane (Anesthesia)",
                   "Xenon"],

    'Attentional Manipulation': ["Attentional Blink",
                                 "Auditory Cueing",
                                 "Crowding",
                                 "Dichotic Listening",
                                 "Distractor induced blindness",
                                 "Dual Task",
                                 "Inattentional Blindness",
                                 "Selective Attention",
                                 "Spatial Cueing"],

    'Caffeine Consumption': ["Caffeine Consumption"],

    'Case Study': ["Bilateral Frontal Affectation",
                   "Blindsight (Case Study)",
                   "Conversion Deafness (Case Study)",
                   "Locked In Syndrome (Case Study)",
                   "Posterior Callosal Section",
                   "Tinnitus (Case Study)",
                   "Unresponsive Wakefulness Syndrome (Case Study)",
                   "Visual Extinction (Case Study)"],

    'Change Blindness': ["Change Blindness"],

    'Cognitive Tasks': ["Executive Control",
                        "Flankers Task",
                        "Language",
                        "Memory",
                        "Task Switching",
                        "Working Memory"],

    'Competition (Binocular)': ["b-CFS",
                              "Binocular Rivalry",
                              "CFS",
                              "Flash Supression"],

    'Competition (Monocular)': ["Bistable percepts"],
    'Competition (Monoaural)': ["Bistable percepts"],
    'Competition (Binaural)': ["Bistable percepts"],
    'Computational Modelling': ["Computational Modelling"],
    'Contour Integration': ["Contour Integration"],
    'Dichoptic Masking': ["Dichoptic Masking"],

    'Direct Stimulation': ["Intracranial Stimulation",
                           "Olfactory Epithelium Stimulation",
                           "tACS",
                           "tDCS",
                           "TMS",
                           "Deep Brain Stimulation"],

    'Disorders of Consciousness': ["Coma",
                                   "Emergence from MCS",
                                   "Epilepsy",
                                   "Minimal Consciousness State",
                                   "Seizures / Unclassified DOC",
                                   "Unresponsive Wakefulness Syndrome (Disorders of Consciousness)"],

    'Drowsiness': ["Drowsiness"],
    'Emotion': ["Emotion"],

    'Expectation': ["Emotional",
                    "Oddball",
                    "Prior Exposure (Expectation)"],

    'Familiarity': ["Own Name",
                    "Prior Exposure (Familiarity)",
                    "Self-Face"],

    'Family Nurture Intervention': ["Family Nurture Intervention"],
    'Figure-Ground': ["Figure-Ground"],
    'Filling In': ["Filling In"],
    'Fusion (Color)': ["Fusion (Color)"],
    'Genetics': ["Genetics"],

    'Illusions': ["Apparent Motion",
                  "Benham's top Illusion",
                  "Flash-grab",
                  "Illusory Limb Movements",
                  "Illusory Motion Reversal",
                  "Illusory Rebound Motion",
                  "Implied Motion",
                  "SAM",
                  "Kanizsa",
                  "Moon Illusion",
                  "Octave Illusion",
                  "Pinna-Brelstaff",
                  "Proprioceptive Illusion",
                  "Tilt Illusion",
                  "Verbal Transformation",
                  "Zwicker Tone"],

    'Imagination': ["Motoric"],
    'Lifespan': ["Lifespan"],
    'Locked In Syndrome': ["Locked In Syndrome"],

    'Masking': ["Backward Masking",
                "Dynamic Masking",
                "Forward Masking",
                "Metacontrast Masking",
                "Object Substitution Masking",
                "Paracontrast Masking",
                "Target Masking"],

    'Mirror Masking': ["Mirror Masking"],
    'Motion Detection': ["Motion Detection"],
    'Motion induced Blindness': ["Motion induced Blindness"],
    'N-Back': ["N-Back"],
    'Pain': ["Pain"],
    'Passive Exposure': ["Passive Exposure"],
    'Pop out': ["Mooney Images"],

    'Psychedelic Drugs': ["Ketamine (Psychedelic Drugs)",
                          "Psilocybin"],

    'Repetition Suppression': ["Repetition Suppression"],
    'Resting State': ["Resting State"],
    'Reward': ["Reward"],

    'Sedation': ["Chloral Hydrate",
                 "Dexmedetomidine (Sedation)",
                 "Dextromethorphan (Sedation)",
                 "Halothane (Sedation)",
                 "Isoflurane (Sedation)",
                 "Ketamine (Sedation)",
                 "Lorazepam",
                 "Medetomidine (Sedation)",
                 "Midazolam (Sedation)",
                 "Nitrous Oxide",
                 "Propofol (Sedation)",
                 "Scopolamine",
                 "Urethane (Sedation)"],

    'Size Constancy': ["Size Constancy"],
    'Sleep': ["Sleep"],
    'Sperling Like': ["Sperling Like"],

    'Stimulus Degradation': ["Brief Presentation",
                             "Coherence Reduction",
                             "Intensity Reduction",
                             "Noise Induction"],

    'SWIFT': ["SWIFT"],
    'Task Relevance': ["Task Relevance"],
    'Visual Persistence': ["Visual Persistence"],
    'Visual Search': ["Visual Search"]
}

ambiguous_paradigms = ['Sedation', 'Anesthesia', 'Case Study', 'Psychedelic Drugs', 'Familiarity',
                       'Abnormal Contents of Consciousness', 'Disorders of Consciousness', 'Expectation']

task_types = ["No Task",
              "Discrimination",
              "Detection",
              "Go/No-Go",
              "Deviant Detection",
              "Stimulus Judgement",
              "Memory",
              "Change Detection",
              "Counting Task",
              "Delayed Task",
              "Task Switching",
              "NBack",
              "Dual Task",
              "Awareness Report",
              "Confidence Report",
              "Binocular Rivalry Task",
              "Visual Search",
              "Identification",
              "NA",
              "Driving",
              "Imagination",
              "Task Switching",
              "Mental Rotation",
              "Color Matching",
              "Mood",
              "Mathematics"]

techniques = ["Ca2 Imaging",
              "Computational Modelling",
              "EEG",
              "fMRI",
              "Intracranial EEG",
              "Intracranial Stimulation",
              "MEG",
              "MRI",
              "PET",
              "tACS",
              "tDCS",
              "TMS"]

finding_tag_types = {
    'Temporal': ["M130",
                 "M280",
                 "M70",
                 "N1",
                 "N140",
                 "N150",
                 "N170",
                 "N2",
                 "N2pc",
                 "N400",
                 "P1",
                 "P2",
                 "P300",
                 "VAN",
                 "CNV",
                 "Recurrent Processing",
                 "MMN",
                 "ART",
                 "ARN",
                 "Early Components",
                 "Late Components",
                 "SN",
                 "Prestimulus Components",
                 "SPCN",
                 "ERN",
                 "Pe",
                 "EPN",
                 "Border Difference",
                 "Figure Ground Difference",
                 "Change related positivity",
                 "AAN",
                 "Intermediate Components"],

    'Spatial Areas': ["Frontal",
                      "Parietal",
                      "Posterior",
                      "Temporal",
                      "Ventral Stream",
                      "V1",
                      "A1",
                      "Dorsal Stream",
                      "DMN",
                      "V4",
                      "S1",
                      "Subcortical structures",
                      "Uncinate Fasciculus",
                      "Dorsal Attention Network",
                      "Visual Network"],

    'Frequency': ["Alpha",
                  "Beta",
                  "Delta",
                  "Gamma",
                  "Theta"
                  ],

    'miscellaneous': ["Acetylcholine",
                      "Anatomic Functional connectivity similarity",
                      "Anterior Posterior Connectivity",
                      "Centrality",
                      "CFC",
                      "Complexity",
                      "Cortical Subcortical connectivity",
                      "Frequency Increase",
                      "Fronto Parietal connectivity",
                      "Global Synchronization",
                      "Hierarchical Structure",
                      "Hyper Synchronization",
                      "Ignition Variability",
                      "inter lobe connectivity",
                      "Low frequencies <1Hz",
                      "Metacognition",
                      "Motor areas connectivity",
                      "PHI Approximation",
                      "Plasticity",
                      "Sleep Spindles",
                      "SCP",
                      "Slow Waves Activity",
                      "Small Worldness",
                      "SSVEP",
                      "Temporal Occipital connectivity",
                      "Temporal Parietal Connectivity",
                      "Ultra slow fluctuations",
                      "Variability",
                      "Intrinsic Ignition",
                      "Local Synchronization",
                      "GABA",
                      "Recurrent Connectivity"]
}

stimulus_category = ["Animals",
                     "Artificial Scenes",
                     "Bodies",
                     "Checkerboard",
                     "Chinese Pictographs",
                     "Color",
                     "Contours",
                     "Digits",
                     "Drawings",
                     "Electric Stimulation",
                     "Epithelium Stimulation",
                     "Faces",
                     "Figure-Ground",
                     "Geometric Shapes",
                     "Gratings",
                     "Kanizsa",
                     "Landolt",
                     "Letters",
                     "Light Flashes",
                     "Motion",
                     "Music",
                     "Natural Scenes",
                     "Nociceptive stimulation",
                     "Noise",
                     "None",
                     "Numbers",
                     "Objects",
                     "Pacman",
                     "Patterns",
                     "Pneumatic stimulations",
                     "Real Objects",
                     "Sexual Images",
                     "Sounds",
                     "Speech",
                     "Symbols",
                     "Textures",
                     "Verniers",
                     "Videos",
                     "Virtual Reality Objects",
                     "Words"]

stimulus_sub_category = {
    'Artificial Scenes': ["Driving Scene"],
    'Color': ["Motion"],
    'Geometric Shapes': ["Arrows",
                         "Motion",
                         "Lines",
                         "Disc",
                         "Dots",
                         "Rings",
                         "Bars",
                         "Circles",
                         "Rectangles",
                         "Squares",
                         "Diamonds",
                         "Color",
                         "Checkerboard",
                         "Meaningless Shape",
                         "Comb of Hexagon",
                         "Octagon"],

    'Gratings': ["Gabor"],
    'Letters': ["Oriented Ts"],
    'Nociceptive stimulation': ["Laser"],
    'Noise': ["White Noise"],

    'Objects': ["Houses",
                "Clocks",
                "Domino",
                "Cars",
                "Coins"],

    'Sounds': ["Tones",
               "Names",
               "Emotional",
               "Clicks",
               "Syllables",
               "Rain",
               "Bubbling Water",
               "Music"],

    'Virtual Reality Objects': ["Houses",
                                "Road",
                                "Moon",
                                "Spheres"],

    'Words': ["Emotional"]

}

finding_tags_map = {"0": "Frontal", "1": "Ventral Stream", "2": "V1", "3": "P300", "4": "VAN", "5": "Gamma",
                    "6": "Complexity", "7": "Local Synchronization", "8": "Global Synchronization",
                    "9": "Fronto Parietal connectivity", "10": "Variability", "11": "A1", "12": "Dorsal Stream",
                    "13": "Beta", "14": "Alpha", "15": "CNV", "16": "Parietal", "17": "DMN", "18": "Small Worldness",
                    "19": "PHI Approximation", "20": "Metacognition", "21": "Posterior", "22": "N2pc",
                    "23": "Recurrent Processing", "24": "GABA", "25": "P2", "26": "MMN", "27": "N2", "28": "Theta",
                    "29": "Delta", "30": "ART", "31": "V4", "32": "Early Components", "33": "Late Components",
                    "34": "Temporal Parietal Connectivity", "35": "S1", "36": "N140", "37": "N170", "38": "Centrality",
                    "39": "N1", "40": "CFC", "41": "Anterior Posterior Connectivity", "42": "Subcortical structures",
                    "43": "Cortical Subcortical connectivity", "44": "Acetylcholine", "46": "SN",
                    "47": "Motor areas connectivity", "48": "Temporal Occipital connectivity",
                    "49": "Prestimulus Components", "50": "Low frequencies <1Hz", "51": "Uncinate Fasciculus",
                    "53": "SPCN", "55": "Figure Ground Difference", "56": "Border Difference", "57": "P1",
                    "58": "Frequency Increase", "59": "Sleep Spindles", "60": "Slow Waves Activity", "62": "ERN",
                    "63": "EPN", "64": "Hyper Synchronization", "65": "Plasticity",
                    "66": "Anatomic Functional connectivity similarity", "67": "Ultra slow fluctuations", "69": "M70",
                    "70": "M130", "71": "ARN", "72": "M280", "74": "N400", "75": "Pe",
                    "76": "Change related positivity",
                    "77": "N150", "78": "Intermediate Components", "79": "SSVEP", "80": "inter lobe connectivity",
                    "81": "Intrinsic Ignition", "82": "Ignition Variability", "83": "Hierarchical Structure",
                    "84": "SCP", "85": "AAN", "86": "Dorsal Attention Network", "87": "Visual Network",
                    "88": "Recurrent Connectivity"
                    }

task_types_mapping = {"0": "No Task", "1": "Discrimination", "2": "Detection", "3": "Go/No-Go",
                      "4": "Deviant Detection",
                      "5": "Stimulus Judgement", "7": "Memory", "8": "Change Detection", "9": "Counting Task",
                      "10": "Delayed Task", "14": "Task Switching", "17": "NBack", "18": "Dual Task",
                      "19": "Awareness Report", "21": "Confidence Report", "22": "Binocular Rivalry Task",
                      "23": "Visual Search", "24": "Identification", "26": "NA", "27": "Driving", "30": "Imagination",
                      "32": "Task Switching", "33": "Mental Rotation", "35": "Color Matching", "36": "Mood",
                      "37": "Mathematics"}

findings_measures = {
    "0": "Decoding",
    "1": "BOLD",
    "2": "Frequencies",
    "3": "ERP",
    "4": "Mutual Information",
    "5": "Synchronization",
    "6": "Behavioral Accuracy",
    "7": "Behavioral RT",
    "9": "Connectivity",
    "10": "PHI",
    "11": "Graph theoretical measures",
    "14": "Entropy",
    "15": "Global Field Power",
    "16": "PCA",
    "17": "Lempel Ziv",
    "18": "H2_15O",
    "19": "Variability",
    "20": "Adaptation",
    "21": "Metacognition",
    "22": "Visibility",
    "25": "Dimension of activation",
    "26": "fALFF",
    "27": "18F Fluorodeoxyglucose",
    "28": "CFC",
    "29": "LRTC",
    "30": "Calcium Imaging",
    "31": "K Complex",
    "32": "TCT",
    "33": "DISS",
    "34": "Observation",
    "35": "Microstates",
    "36": "Stimulation Reactivity",
    "37": "Frequency Tagging",
    "39": "Hopf bifurcation parameter",
    "41": "Slow Wave Activity",
    "42": "Auto Information Flow",
    "43": "Cross Information Flow ciF",
    "44": "PCI",
    "47": "Physiological Measure",
    "49": "Computer Simulations",
    "50": "Phosphene Threshold",
    "51": "Frequency Change Index",
    "52": "Brain Behavior Correlation",
    "56": "DSI",
    "58": "Complexity of functional connectivity",
    "63": "BIS",
    "64": "Correlation dimension",
    "65": "Dominance",
    "66": "Epileptogenicity Index",
    "67": "Spike Suppression",
    "68": "Mean Dwell Time",
    "69": "Network Backbones",
    "70": "SSVEP",
    "71": "Fractal Dimension"
}

AAL_tags = [
    "Precentral",
    "Frontal_Sup",
    "Frontal_Mid",
    "Frontal_Inf_Oper",
    "Frontal_Inf_Tri",
    "Frontal_Inf_Orb",
    "Rolandic_Oper",
    "Supp_Motor_Area",
    "Olfactory",
    "Frontal_Sup_Med",
    "Frontal_Med_Orb",
    "Rectus",
    "OFCmed",
    "OFCant",
    "OFCpost",
    "OFClat",
    "Insula",
    "Cingulate_Ant",
    "Cingulate_Ant",
    "Cingulate_Mid",
    "Cingulate_Post",
    "Hippocampus",
    "ParaHippocampal",
    "Amygdala",
    "Calcarine",
    "Cuneus",
    "Lingual",
    "Occipital_Sup",
    "Occipital_Mid",
    "Occipital_Inf",
    "Fusiform",
    "Postcentral",
    "Parietal_Sup",
    "Parietal_Inf",
    "SupraMarginal",
    "Angular",
    "Precuneus",
    "Paracentral_Lobule",
    "Caudate",
    "Putamen",
    "Pallidum",
    "Thalamus",
    "Heschl",
    "Temporal_Sup",
    "Temporal_Pole_Sup",
    "Temporal_Mid",
    "Temporal_Pole_Mid",
    "Temporal_Inf",
    "Thal_AV",
    "Thal_LP",
    "Thal_VA",
    "Thal_VL",
    "Thal_VPL",
    "Thal_IL",
    "Thal_RE",
    "Thal_MDm",
    "Thal_MDl",
    "Thal_LGN",
    "Thal_MGN",
    "Thal_PuA",
    "Thal_PuM",
    "Thal_PuL",
    "Thal_PuI"
]
