paradigms = {
    'parent_paradigms': [
        "Abnormal Contents of Consciousness",
        "Alcohol Consumption",
        "Anesthesia",
        "Attentional Manipulation",
        "Caffeine Consumption",
        "Case Study",
        "Change Blindness",
        "Cognitive Tasks",
        "Competition (Binocular)",
        "Competition (Monocular)",
        "Computational Modelling",
        "Contour Integration",
        "Dichoptic Masking",
        "Direct Stimulation",
        "Disorders of Consciousness",
        "Drowsiness",
        "Emotion",
        "Expectation",
        "Familiarity",
        "Family Nurture Intervention",
        "Figure-Ground",
        "Filling In",
        "Fusion (Color)",
        "Genetics",
        "Illusions",
        "Imagination",
        "Lifespan",
        "Locked In Syndrome",
        "Masking",
        "Mirror Masking",
        "Motion Detection",
        "Motion induced Blindness",
        "N-Back",
        "Pain",
        "Passive Exposure",
        "Pop out",
        "Psychedelic Drugs",
        "Repetition Suppression",
        "Resting State",
        "Reward",
        "Sedation",
        "Size Constancy",
        "Sleep",
        "Sperling Like",
        "Stimulus Degradation",
        "SWIFT",
        "Task Relevance",
        "Visual Persistence",
        "Visual Search"],

    'Abnormal_Contents_of_Consciousness': ["Amusia",
                                           "Blindsight",
                                           "Conversion Deafness",
                                           "Hypoactive delirium",
                                           "Neglect",
                                           "Parkinson Disease",
                                           "Schizophrenia",
                                           "Synesthesia",
                                           "Tinnitus",
                                           "Visual Extinction"],

    'Anesthesia': ["Dexmedetomidine",
                   "Dextromethorphan",
                   "Enflurane",
                   "Halothane",
                   "Isoflurane",
                   "Ketamine",
                   "Medetomidine",
                   "Midazolam",
                   "Pancuronium",
                   "Propofol",
                   "Sevoflurane",
                   "Sufentanil",
                   "Urethane",
                   "Xenon"],

    'Attentional_Manipulation': ["Attentional Blink",
                                 "Auditory Cueing",
                                 "Crowding",
                                 "Dichotic Listening",
                                 "Distractor induced blindness",
                                 "Dual Task",
                                 "Inattentional Blindness",
                                 "Selective Attention",
                                 "Spatial Cueing"],

    'Case_Study': ["Bilateral Frontal Affectation",
                   "Blindsight (Case Study)",
                   "Conversion Deafness (Case Study)",
                   "Locked In Syndrome (Case Study)",
                   "Posterior Callosal Section",
                   "Tinnitus (Case Study)",
                   "Unresponsive Wakefulness Syndrome (Case Study)",
                   "Visual Extinction (Case Study)"],

    'Cognitive_Tasks': ["Executive Control",
                        "Flankers Task",
                        "Language",
                        "Memory",
                        "Task Switching",
                        "Working Memory"],

    'Competition_Binocular': ["b-CFS",
                              "Binocular Rivalry",
                              "Bistable percepts",
                              "CFS",
                              "Flash Supression"],

    'Direct_Stimulation': ["Intracranial Stimulation",
                           "Olfactory Epithelium Stimulation",
                           "tACS",
                           "tDCS",
                           "TMS",
                           "Deep Brain Stimulation"],

    'Disorders_of_Consciousness': ["Coma",
                                   "Emergence from MCS",
                                   "Epilepsy",
                                   "Minimal Consciousness State",
                                   "Seizures / Unclassified DOC",
                                   "Unresponsive Wakefulness Syndrome"],

    'Illusions': ["Apparent Motion",
                  "Benham's top Illusion",
                  "Flash-grab",
                  "Illusory Limb Movements",
                  "Illusory Motion Reversal",
                  "Illusory Rebound Motion",
                  "Implied Motion",
                  "SAM",
                  "Kanizsa",
                  "Moon Illusion",
                  "Octave Illusion",
                  "Pinna-Brelstaff",
                  "Proprioceptive Illusion",
                  "Tilt Illusion",
                  "Verbal Transformation",
                  "Zwicker Tone"],

    'Masking': ["Backward Masking",
                "Dynamic Masking",
                "Forward Masking",
                "Metacontrast Masking",
                "Object Substitution Masking",
                "Paracontrast Masking",
                "Target Masking"],

    'Sedation': ["Chloral Hydrate",
                 "Dexmedetomidine (Sedation)",
                 "Dextromethorphan (Sedation)",
                 "Halothane (Sedation)",
                 "Isoflurane (Sedation)",
                 "Ketamine (Sedation)",
                 "Lorazepam",
                 "Medetomidine (Sedation)",
                 "Midazolam (Sedation)",
                 "Nitrous Oxide",
                 "Propofol (Sedation)",
                 "Scopolamine",
                 "Urethane (Sedation)"]
}

task_types = ["No Task",
              "Discrimination",
              "Detection",
              "Go/No-Go",
              "Deviant Detection",
              "Stimulus Judgement",
              "Memory",
              "Change Detection",
              "Counting Task",
              "Delayed Task",
              "Task Switching",
              "NBack",
              "Dual Task",
              "Awareness Report",
              "Confidence Report",
              "Binocular Rivalry Task",
              "Visual Search",
              "Identification",
              "NA",
              "Driving",
              "Imagination",
              "Task Switching",
              "Mental Rotation",
              "Color Matching",
              "Mood",
              "Mathematics"]

techniques = ["Ca2 Imaging",
              "Computational Modelling",
              "EEG",
              "fMRI",
              "Intracranial EEG",
              "Intracranial Stimulation",
              "MEG",
              "MRI",
              "PET",
              "tACS",
              "tDCS",
              "TMS"]

finding_tag_types = {
    'Temporal': ["M130"
                 "M280"
                 "M70"
                 "N1"
                 "N140"
                 "N150"
                 "N170"
                 "N2"
                 "N2pc"
                 "N400"
                 "P1"
                 "P2"
                 "P300"
                 "VAN"
                 "CNV"
                 "Recurrent Processing"
                 "MMN"
                 "ART"
                 "Early Components"
                 "Late Components"
                 "SN"
                 "Prestimulus Timing"
                 "SPCN"
                 "ERN"
                 "Pe"
                 "EPN"
                 "Border Difference"
                 "Figure Ground difference"
                 "Change related positivity"
                 "AAN"
                 "Intermediate Components"],

    'Spatial_Areas': ["Frontal",
                      "Parietal",
                      "Posterior",
                      "Temporal",
                      "Ventral Stream",
                      "V1",
                      "A1",
                      "Dorsal Stream",
                      "DMN",
                      "V4",
                      "S1",
                      "Subcortical structures",
                      "Uncinate Fasciculus",
                      "Dorsal Attention Network",
                      "Visual Network"],

    'miscellaneous': ["Acetylcholine",
                      "Anatomic Functional connectivity similarity",
                      "Anterior Posterior Connectivity",
                      "Centrality",
                      "CFC",
                      "Complexity",
                      "Cortical Subcortical connectivity",
                      "Metacognition",
                      "Motor areas connectivity",
                      "PHI Approximation",
                      "Plasticity",
                      "Slow Waves Activity",
                      "Small Worldness",
                      "SSVEP",
                      "Temporal Occipital connectivity",
                      "Temporal Parietal Connectivity",
                      "Ultra slow fluctuations",
                      "Uncinate Fasciculus",
                      "Variability",
                      "Intrinsic Ignition",
                      "Local Synchronization"]
}

stimulus_category = ["Animals",
                     "Artificial Scenes",
                     "Bodies",
                     "Checkerboard",
                     "Chinese Pictographs",
                     "Color",
                     "Contours",
                     "Digits",
                     "Drawings",
                     "Electric Stimulation",
                     "Epithelium Stimulation",
                     "Faces",
                     "Figure-Ground",
                     "Geometric Shapes",
                     "Gratings/Kanizsa",
                     "Landolt",
                     "Letters",
                     "Light Flashes",
                     "Motion",
                     "Music",
                     "Natural Scenes",
                     "Nociceptive stimulation",
                     "Noise",
                     "None",
                     "Numbers",
                     "Objects",
                     "Pacman",
                     "Patterns",
                     "Pneumatic stimulations",
                     "Real Objects",
                     "Sexual Images",
                     "Sounds",
                     "Speech",
                     "Symbols",
                     "Textures",
                     "Verniers",
                     "Videos",
                     "Virtual Reality Objects",
                     "Words"]

stimulus_sub_category = {
    'Geometric_Shapes': ["Arrows",
                         "Motion",
                         "Lines",
                         "Disc",
                         "Dots",
                         "Rings",
                         "Bars Circles",
                         "Rectangles",
                         "Squares",
                         "Diamonds"]
}
